### ISSUE TITLE
For a PC  [NODE], there is no context shown.

### ISSUE THREAD

**Issue by kairibu** [DSD-DBS/capellambse-context-diagrams#24]
For a PC [NODE], without any Physical Functions, but with deployed PC [BEHAVIOR], and Physical Links to other PC [NODE], there is no context shown, just a yellow box. Is this expected?

For this model:
![grafik](https://user-images.githubusercontent.com/485955/197741479-e793aee4-7ada-4252-b0cf-4cab561e3273.png)

The output of `model.pa.all_components.by_name("PC 37").context_diagram` looks as follows:
![grafik](https://user-images.githubusercontent.com/485955/197741790-d04229be-0b6d-4818-9200-de750dbba0d5.png)

**Comment by ewuerger** [comment]
That is a bug in the context collection stage. With PR #23 contexts of Nodes (`PhysicalLink`s) and Behavior (`ComponentExchange`s) PCs are collected. After this is reviewed and merged you should be able to see nodes in a node context and behavior PCs in a behavior PC context.

The interface context (here: Context on either `PhysicalLink` or `ComponentExchange`) is in general more complicated. There context collection is only implemented for `System` and `Logical` `ComponentExchange`s for now.

Right now I'm working on a free context collection algorithm in PR #20 that enables collection via given context description (YAML file or dictionary). This solution has in theory more scaling than implementing individual context collection logic via functions. Then there is only need for maintenance of individual source/target translation (cost-side) and way more degrees of freedom in context design.
