### ISSUE TITLE
Component Ports without exchanges have transparent background

### ISSUE THREAD

**Issue by Wuestengecko** [DSD-DBS/capellambse-context-diagrams#50]
In context diagrams for Components, ports which do not have a connected Component Exchange are rendered with transparent background. See the two bottommost ports on the left side:

![grafik](https://github.com/DSD-DBS/capellambse-context-diagrams/assets/1579756/bf338f9e-aa0c-49f1-95f4-7426cbb4a5d7)

**Comment by ewuerger** [comment]
These two physical ports (styleclass PP) are not in the generated stylesheet for `SAB` diagrams. These ports shouldn't be collected at all. This bug is fixed in PR #51.
