### ISSUE TITLE
Introduce realization_view for activities / functions

### ISSUE THREAD

**Issue by vik378** [DSD-DBS/capellambse-context-diagrams#59]
Given an activity / function object, lets add a method "realization_view" that would show what functions from the levels below and/or above realize it and what components / entities this functions belong to (who is responsible for it)

**Parameters:**
- Depth should be defaulted to 1, but could be manually tuned up to all layers below. 
- direction (of search): layers above, layers below, all; default: all
- show owning (responsible) components / entities; default: true

**Examples**

- realization_view called on Function 1 with depth 1 and direction "above" and show_owners=True
   ![image](https://github.com/DSD-DBS/capellambse-context-diagrams/assets/8280844/92d02cdd-c432-4f20-a120-b0114b0641c9)

- realization_view called on Activity, depth 1, direction "below", show owners=True
   ![image](https://github.com/DSD-DBS/capellambse-context-diagrams/assets/8280844/0383c03a-0867-4d7b-bb0e-74dd9ff4b144)

**Comment by MS34449** [comment]
Could we add an example for the other graphical variant using "wrapper boxes", that we have discussed already?

Here is the Capella forum thread I have started on this topic, some ways to present realisation links are discussed there (title blocks, matrices), but none of them meet the need for a clean visual representation:

https://forum.mbse-capella.org/t/cross-level-realisation-links-in-diagrams/6462/3

**Comment by ewuerger** [comment]
Solved by #63. Therefore closed.
